<a href="https://colab.research.google.com/github/23spakkerakari/pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
#now, we'll introduce ourself to tensors by comparing lists, numpy arrays and tensors. One is just a more complex, applicable, feature-loaded version of the next

In [3]:
list1 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [5]:
np1 = np.random.rand(3, 4)
np1

array([[0.1494241 , 0.35341098, 0.31574206, 0.68223315],
       [0.12239736, 0.80496666, 0.36904222, 0.6141545 ],
       [0.28445208, 0.82370479, 0.47028049, 0.15020369]])

In [7]:
np1.dtype

dtype('float64')

In [8]:
t1 = torch.randn(3, 4)
t1 #creates a 3x4 random matrix

tensor([[ 1.6568, -2.4054, -0.3625, -1.6083],
        [ 1.8648,  0.8203, -0.3097, -1.4011],
        [ 0.6719, -0.0861,  0.9332, -0.9751]])

In [9]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d #creates a 3d matrix


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#can reshape a tensor just like numpy
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
#if we instead do rows x columns where columns = -1, it will evenly divide the total count in the tensor evenly by the number of rows
my_torch2 = my_torch.reshape(2, -1)
my_torch3 = torch.arange(15).reshape(3, -1)
my_torch2
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [23]:
my_torch4 = my_torch3.view(5, 3)
my_torch4[2] = 56 # If you make a change to one, you change all the other tensors that are connected to it
my_torch4
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5, 56, 56, 56,  9],
        [10, 11, 12, 13, 14]])

In [26]:
#MATH OPERATIONS

ta = torch.tensor([1, 2, 3, 4])
tb = torch.tensor([5, 6, 7, 8])

In [27]:
ta + tb #sums each respective element into one tensor

tensor([ 6,  8, 10, 12])

In [28]:
torch.sub(ta, tb)

tensor([-4, -4, -4, -4])

In [30]:
ta * tb
torch.mul(ta, tb)

tensor([ 5, 12, 21, 32])

In [31]:
tb/ta
torch.divide(tb, ta)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [32]:
#remainder

tb % ta

tensor([0, 0, 1, 0])

In [33]:
torch.pow(ta, tb)

tensor([    1,    64,  2187, 65536])

In [34]:
import torch.nn as nn